inherit_from: .rubocop_todo.yml

# Use %x for command literal since backticks are less clear and discouraged
# in modern shell programming.
Style/CommandLiteral:
  EnforcedStyle: percent_x

# Use brackets for symbol array for clarity.
Style/SymbolArray:
  EnforcedStyle: brackets
